#!/bin/sh
# Test that unzipping a single pkzip file works

# Copyright (C) 2013-2019 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# limit so don't run it by default.

. "${srcdir=.}/init.sh"; path_prepend_ ..
cp ../../configure in || framework_failure_
cp in in_copy || framework_failure_

# create zip file. If zip file cannot be created, then return
# frameworkd_failure_
zip -m in.gz in || framework_failure_

fail=0

# Test if decompression from stdin works
gzip -d < in.gz > in || fail=1
compare in in_copy || fail=1
rm in

# Test if decompression from a file works
gzip -d in.gz || fail = 1
compare in in_copy || fail=1

# Test small inputs
rm in in_copy
echo "pkzip" > in
cp in in_copy
zip -m in.gz in || framework_failure_

# Test if decompression from stdin works
gzip -d < in.gz > in || fail=1
compare in in_copy || fail=1
rm in

# Test if decompression from a file works
gzip -d in.gz || fail = 1
compare in in_copy || fail=1

rm in in_copy
Exit $fail
